// apps/mfe-webcomponent-education/src/single-spa.ts
import { emitMfeError, emitMfeState } from "@my-portal/utils";
import EducationApp from './components/EducationElement';

let domElement: HTMLElement | null = null;
let appRoot: HTMLElement | null = null;

export async function bootstrap() {
  if (!customElements.get('education-app')) {
    customElements.define('education-app', EducationApp);
  }
  return Promise.resolve();
}

export async function mount(props: { domElementGetter: () => HTMLElement }) {
  emitMfeState('mfe-webcomponent-education', 'loading', 'Preparing Web Components education page...');
  try {
    domElement = props.domElementGetter();
    if (!domElement) throw new Error('Missing dom element for education MFE');
    domElement.innerHTML = '';
    appRoot = document.createElement('education-app');
    domElement.appendChild(appRoot);
    emitMfeState('mfe-webcomponent-education', 'ready', 'Web Components education page is ready.');
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    emitMfeError('mfe-webcomponent-education', message);
    return Promise.reject(error);
  }
  return Promise.resolve();
}

export async function unmount() {
  if (domElement && appRoot) {
    domElement.removeChild(appRoot);
    appRoot = null;
  }
  return Promise.resolve();
}

// apps/mfe-react-home/src/single-spa.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import singleSpaReact from "single-spa-react";
import { HomePage as HomeApp } from "./components";
import { emitMfeError, emitMfeState } from "@my-portal/utils";

const baseLifecycles = singleSpaReact({
  React,
  ReactDOMClient: ReactDOM,
  rootComponent: HomeApp,
  domElementGetter: (props: { domElementGetter?: () => HTMLElement }) =>
    props.domElementGetter ? props.domElementGetter() : (document.getElementById("mfe-container") as HTMLElement),
  errorBoundary: () => <div>Failed to load Home MFE.</div>
});

export const bootstrap = baseLifecycles.bootstrap;

export async function mount(props: Parameters<typeof baseLifecycles.mount>[0]) {
  emitMfeState("mfe-react-home", "loading", "Preparing React experience...");
  try {
    await baseLifecycles.mount(props);
    emitMfeState("mfe-react-home", "ready", "React experience ready.");
  } catch (error) {
    emitMfeState("mfe-react-home", "error", "Unable to render React page.");
    emitMfeError("mfe-react-home", error instanceof Error ? error.message : "Unknown React mount error.");
    throw error;
  }
}

export const unmount = baseLifecycles.unmount;

if (!(window as { singleSpaNavigate?: unknown }).singleSpaNavigate) {
  const root = ReactDOM.createRoot(document.getElementById("root")!);
  root.render(<HomeApp />);
}
